name: Comment
on:
  issues:
    types: [opened]
jobs:
  assignTroy:
    name: Comment on issue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Label issue
        uses: actions/github@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: comment "Thank you for opening an issue, Troy will take care of it"
